version: "3.9"
services:
  discord-bot:
    container_name: discord-bot
    restart: "unless-stopped"
    depends_on:
      - mongodb
    environment:
      - ENV=CONTAINER
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - PREFIX=${PREFIX}
      - MONGO_HOST_NAME=mongodb
      - MONGO_ROOT_USER=${MONGO_ROOT_USER}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INTERNAL_PORT=${MONGO_INTERNAL_PORT}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_OPTIONS=${MONGO_OPTIONS}
    networks:
      - mongo-discord-bot-network
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/ronniegeraghty/discord-bot:2.0.4
  mongodb:
    container_name: mongodb-discord-bot
    image: mongo:5.0.2
    restart: "unless-stopped"
    hostname: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    ports:
      - "${MONGO_EXTERNAL_PORT}:27017"
    volumes:
      - ${MONGO_VOLUME_MOUNT}:/data/db
    networks:
      - mongo-discord-bot-network
networks:
  mongo-discord-bot-network:
    driver: bridge
