name: "Git Tag & Push"
description: "Create a Git Tag and Push to GitHub"
inputs:
  tag:
    description: "tag to be used"
    required: true
  github-auth:
    description: "API auth token for GitHub with access to tags api"
    required: true
outputs:
  success: # id of output
    description: "Was the step successful in creating and pushing the tag"
runs:
  using: "node16"
  main: "index.js"
branding:
  icon: tag
  color: blue
