name: "Create Docker Tag"
description: "Creates the docker tag to use based on the current git tag"
inputs:
  image: # id of input
    description: "registry/container-name"
    required: true
outputs:
  tag: # id of output
    description: "tag for the docker container"
runs:
  using: "node16"
  main: "index.js"
