# This is a basic workflow to help you get started with Actions
name: Docker Build & Publish
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ main ]
  push: 
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  docker-build-publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: 
      PUSH_PACKAGES: ${{github.event_name == 'push' && github.ref == 'refs/heads/main'}}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
      # Check PUSH_PACKAGE variable
      - name: Check PUSH_PACKAGE
        run: echo ${{env.PUSH_PACKAGE}}
      # Set up QEMU for emulation to build against other platforms
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # Set up Docker Buildx
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # Login to GHCR
      - name: Login to GitHub Container Registry
        if: ${{env.PUSH_PACKAGES}}
        uses: docker/login-action@v1
        with: 
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      # Run Docker build
      - name: Run Docker Build & Publish
        uses: docker/build-push-action@v2
        with: 
          push: ${{env.PUSH_PACKAGES}}
          context: .
      - name: Image digest
        run: echo ${{steps.docker_build.outputs.digest}}
